apiVersion: v1
kind: Service
metadata:
  labels:
    app: ec2
  name: ec2
  namespace: default
spec:
  clusterIP: ""
  externalName: 
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
  type: ExternalName

